import fs from 'node:fs';
import path from 'node:path';
import { SYMBOLS } from '../market/symbols.js';
import { MarketData } from '../market/marketData.js';
import { SimFeed } from '../market/simFeed.js';
import { nyTimeOnSameDay, nyParts } from '../market/session.js';
import { yahoo as yahooClient, toBars as yahooBars } from '../market/yahooClient.js';

// Long 1-minute history for the research desks (the live feeds only keep 15 hours).
//
// Live mode: about two weeks of real bars (Binance for crypto, Yahoo Finance for the rest,
// the broker's own bars once MT5 prices a market), cached in data/history/ and extended with
// every new bar, so research gets better the longer the floor runs. Only real data is ever
// saved. Simulation (demo) mode: past sessions are
// generated by the same market simulator, including the same economic calendar shocks, so
// the desks research the market they actually trade. When a simulated market gets real
// prices (Yahoo answers again, or MT5 takes it over) its generated history is thrown away
// and replaced by the real bars, and research desks re-test on them.

const MAX_BARS = 20_000;
const CACHE_VERSION = 2;
const BINANCE_HOSTS = ['https://api.binance.com', 'https://data-api.binance.vision'];
// History sources that are real market data (as opposed to 'simulated' or 'none').
const REAL_SOURCES = new Set(['binance', 'yahoo', 'saved', 'broker']);

// b wins where both have a bar for the same minute.
function mergeBars(a, b) {
  const map = new Map();
  for (const x of a) map.set(x.time, x);
  for (const x of b) map.set(x.time, x);
  return [...map.values()].sort((x, y) => x.time - y.time).slice(-MAX_BARS);
}

// Shift `bars` onto the price level of `ref` (e.g. Yahoo's futures prices onto the broker's
// CFD prices) using the median gap over the minutes both have. null when they don't overlap.
export function alignTo(bars, ref) {
  if (!bars.length || !ref.length) return bars;
  const byTime = new Map(bars.map((b) => [b.time, b]));
  const gaps = [];
  for (let i = ref.length - 1; i >= 0 && gaps.length < 120; i--) {
    const b = byTime.get(ref[i].time);
    if (b) gaps.push(ref[i].close - b.close);
  }
  if (!gaps.length) return null;
  gaps.sort((x, y) => x - y);
  const off = gaps[Math.floor(gaps.length / 2)];
  return off ? bars.map((b) => ({ ...b, open: b.open + off, high: b.high + off, low: b.low + off, close: b.close + off })) : bars;
}

const isWeekend = (ms) => ['Sat', 'Sun'].includes(nyParts(ms).weekday);

const pause = () => new Promise((r) => setImmediate(r));

// Past simulated sessions ending just before `endSec`, for the given symbols (yields to the
// event loop between sessions so the floor stays responsive while it generates).
export async function syntheticHistory(ids, { endSec, sessions = 30, calendar = null, seed = 7, sessionShape = true, minutes = 12_000 }) {
  let t = 0;
  const clock = { now: () => t, mode: 'sim' };
  const md = new MarketData(clock);
  const out = Object.fromEntries(ids.map((id) => [id, []]));
  md.on('bar', (id, bar) => out[id]?.push(bar));
  const sim = new SimFeed(md, clock, ids, { seed, calendar, useSessionShape: sessionShape });
  if (sessionShape) {
    // Cash sessions 09:30–16:00 New York on the weekdays before endSec.
    const days = [];
    let d = endSec * 1000 - 86_400_000;
    while (days.length < sessions) {
      if (!isWeekend(d)) days.unshift(nyTimeOnSameDay(d, 16, 0));
      d -= 86_400_000;
    }
    let prevClose = null;
    for (const close of days) {
      const open = close - 390 * 60_000;
      if (prevClose) sim.gap(prevClose, open);
      t = close;
      sim.warmup(390);
      prevClose = close;
      await pause();
    }
  } else {
    for (let done = 0; done < minutes; done += 600) {
      const chunk = Math.min(600, minutes - done);
      t = endSec * 1000 - 60_000 - (minutes - done - chunk) * 60_000;
      sim.warmup(chunk);
      await pause();
    }
  }
  return out;
}

async function fetchJson(url, timeoutMs = 12_000, headers = {}) {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), timeoutMs);
  try {
    const res = await fetch(url, { signal: ctrl.signal, headers });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    return await res.json();
  } finally {
    clearTimeout(timer);
  }
}

async function binanceHistory(ticker, pages = 10) {
  let lastErr;
  for (const host of BINANCE_HOSTS) {
    try {
      let end = Date.now();
      let bars = [];
      for (let p = 0; p < pages; p++) {
        const rows = await fetchJson(`${host}/api/v3/klines?symbol=${ticker}&interval=1m&limit=1000&endTime=${end}`);
        if (!rows.length) break;
        bars = rows.map((k) => ({ time: Math.floor(k[0] / 1000), open: +k[1], high: +k[2], low: +k[3], close: +k[4], volume: +k[5] })).concat(bars);
        end = rows[0][0] - 1;
      }
      bars.pop(); // still forming
      return bars;
    } catch (err) {
      lastErr = err;
    }
  }
  throw lastErr;
}

// Two weeks of 1-minute bars from Yahoo, through the floor's rate-limit-aware client.
async function yahooHistory(ticker, chunks = 2) {
  const now = Math.floor(Date.now() / 1000);
  let bars = [];
  for (let c = 0; c < chunks; c++) {
    const p2 = now - c * 7 * 86400;
    const p1 = p2 - 7 * 86400 + 60;
    try {
      const result = await yahooClient.chart(ticker, `interval=1m&period1=${p1}&period2=${p2}&includePrePost=true`, 15_000);
      bars = mergeBars(bars, yahooBars(result));
    } catch (err) {
      if (c === 0) throw err;
    }
  }
  if (bars.length) bars.pop();
  return bars;
}

export class HistoryStore {
  constructor({ md, mode, dataDir = null, calendar = null, log = console, fetchers = null }) {
    this.md = md;
    this.mode = mode;
    this.calendar = calendar;
    this.log = log;
    this.dir = dataDir && mode !== 'sim' ? path.join(dataDir, 'history') : null;
    this.fetchers = fetchers || { binance: binanceHistory, yahoo: yahooHistory };
    this.store = new Map(Object.keys(SYMBOLS).map((id) => [id, []]));
    this.info = new Map(Object.keys(SYMBOLS).map((id) => [id, { source: 'none', status: 'waiting' }]));
    this.ready = false;
    this.pendingClaims = new Map(); // real prices that took over a market while history was loading
    md.on('bar', (id, bar) => this.#append(id, bar));
    md.on('rebase', (id, offset) => {
      for (const b of this.store.get(id) || []) {
        b.open += offset; b.high += offset; b.low += offset; b.close += offset;
      }
    });
    md.on('claim', (id, source, bars) => this.#onClaim(id, source, bars));
  }

  // Is this market's research history real market data?
  isReal(id) {
    return this.mode !== 'sim' && REAL_SOURCES.has(this.info.get(id)?.source);
  }

  // The price level the stored bars are on: the broker's own prices once MT5 owns the
  // market, otherwise the public feed's.
  #level(id) {
    return this.md.ownerOf(id) === 'mt5' ? 'mt5' : SYMBOLS[id].source.type;
  }

  #append(id, bar) {
    const arr = this.store.get(id);
    if (!arr) return;
    const lastBar = arr[arr.length - 1];
    if (lastBar && bar.time <= lastBar.time) return;
    arr.push({ time: bar.time, open: bar.open, high: bar.high, low: bar.low, close: bar.close, volume: bar.volume });
    if (arr.length > MAX_BARS + 500) arr.splice(0, arr.length - MAX_BARS);
  }

  // All stored bars with the feed's latest closed bars merged in (oldest first).
  bars(id) {
    const arr = this.store.get(id) || [];
    const live = this.md.bars(id);
    const lastT = arr.length ? arr[arr.length - 1].time : -Infinity;
    const tail = live.filter((b) => b.time > lastT);
    return tail.length ? arr.concat(tail) : arr;
  }

  recent(id, n) {
    const all = this.bars(id);
    return all.length > n ? all.slice(-n) : all;
  }

  status() {
    const out = {};
    for (const [id, arr] of this.store) out[id] = { ...this.info.get(id), bars: this.bars(id).length, from: arr[0]?.time ?? null };
    return out;
  }

  async load() {
    const ids = Object.keys(SYMBOLS);
    // Generated history is for demo mode only: live mode researches real market data or
    // waits for it.
    const simIds = this.mode === 'sim' ? ids : [];
    const liveIds = ids.filter((id) => !simIds.includes(id));
    if (simIds.length) await this.#loadSynthetic(simIds);
    await Promise.all(liveIds.map((id) => this.#loadLive(id)));
    this.ready = true;
    for (const [id, c] of this.pendingClaims) this.#adopt(id, c.source, c.bars);
    this.pendingClaims.clear();
    if (this.dir) {
      this.saveTimer = setInterval(() => this.save(), 15 * 60_000);
      this.saveTimer.unref?.();
    }
  }

  async #loadSynthetic(ids) {
    const first = Object.fromEntries(ids.map((id) => [id, this.md.bars(id)[0]]));
    const endSec = Math.min(...ids.map((id) => first[id]?.time ?? Math.floor(Date.now() / 1000)));
    const gen = await syntheticHistory(ids, {
      endSec, calendar: this.calendar, seed: (endSec % 100_000) + 17,
      sessionShape: this.mode === 'sim',
    });
    for (const id of ids) {
      let bars = gen[id] || [];
      // Line the generated history up with where the live simulation starts.
      const anchor = first[id]?.open;
      const lastBar = bars[bars.length - 1];
      if (anchor && lastBar) {
        const k = anchor / lastBar.close;
        bars = bars.map((b) => ({ ...b, open: b.open * k, high: b.high * k, low: b.low * k, close: b.close * k }));
      }
      bars = bars.filter((b) => b.time < endSec);
      this.store.set(id, mergeBars(bars, this.md.bars(id)));
      this.info.set(id, { source: 'simulated', status: 'ready' });
    }
  }

  #cacheFile(id) {
    return this.dir ? path.join(this.dir, `${id}.json`) : null;
  }

  // { level, bars } from data/history, or null. Caches from older versions are ignored:
  // they could hold generated (simulated) bars.
  #readCache(id) {
    if (!this.dir) return null;
    try {
      const raw = JSON.parse(fs.readFileSync(this.#cacheFile(id), 'utf8'));
      if (raw?.v !== CACHE_VERSION || !Array.isArray(raw.bars)) return null;
      const bars = raw.bars.map(([time, open, high, low, close, volume]) => ({ time, open, high, low, close, volume }));
      return bars.length ? { level: raw.level, bars } : null;
    } catch {
      return null; // no cache yet
    }
  }

  async #loadLive(id) {
    const sym = SYMBOLS[id];
    const level = this.#level(id);
    const cache = this.#readCache(id);
    let bars = cache?.level === level ? cache.bars : [];
    let source = bars.length ? 'saved' : 'none';
    try {
      let fetched = sym.source.type === 'binance' ? await this.fetchers.binance(sym.source.ticker) : await this.fetchers.yahoo(sym.source.ticker);
      // The broker (MT5) already prices this market: move the public feed's history onto
      // its price level, or leave it out if the two can't be lined up.
      if (fetched.length && level === 'mt5') fetched = alignTo(fetched, mergeBars(bars, this.md.bars(id))) || [];
      if (fetched.length) {
        // The broker's own saved bars beat shifted public ones; otherwise the fresh fetch wins.
        bars = level === 'mt5' ? mergeBars(fetched, bars) : mergeBars(bars, fetched);
        source = sym.source.type;
      }
    } catch (err) {
      this.log.warn?.(`[research] ${id}: could not load long history (${err.message})${bars.length ? ' — using the saved copy' : ''}`);
    }
    // MT5 took the market over while we were fetching: line the history up with its prices.
    const live = this.md.bars(id);
    if (this.#level(id) !== level && bars.length) bars = alignTo(bars, live) || [];
    this.store.set(id, mergeBars(bars, live));
    // Nothing loaded: the store still fills from this market's real feed, bar by bar.
    if (source === 'none') source = this.#level(id) === 'mt5' ? 'broker' : sym.source.type;
    this.info.set(id, { source, status: 'ready' });
  }

  #onClaim(id, source, bars) {
    if (this.mode === 'sim' || !['mt5', 'yahoo', 'binance'].includes(source)) return;
    const copy = bars.filter((b) => Number.isFinite(b.close) && b.close > 0).map((b) => ({ time: b.time, open: b.open, high: b.high, low: b.low, close: b.close, volume: b.volume }));
    if (!this.ready) this.pendingClaims.set(id, { source, bars: copy });
    else this.#adopt(id, source, copy);
  }

  // Real prices took over a market (the broker's MT5 feed, or Yahoo answering again): make
  // its research history real too. Generated bars are thrown away; real history from
  // another feed is shifted onto the new price level; the new source's bars win.
  #adopt(id, source, claimed) {
    if (!claimed.length) return;
    const level = source === 'mt5' ? 'mt5' : SYMBOLS[id].source.type;
    const wasReal = this.isReal(id);
    let base = wasReal ? alignTo(this.store.get(id), claimed) ?? this.store.get(id) : [];
    const cache = this.#readCache(id);
    if (cache?.level === level) base = mergeBars(base, cache.bars);
    this.store.set(id, mergeBars(base, claimed));
    this.info.set(id, { source: level === 'mt5' ? 'broker' : level, status: 'ready' });
    if (!wasReal) this.log.info?.(`[research] ${id}: research history is now real ${level === 'mt5' ? 'broker' : 'market'} data (${this.store.get(id).length.toLocaleString('en-US')} bars)`);
    // A market back on Yahoo: fetch its longer history too (once, politely).
    if (!wasReal && level === 'yahoo') this.#extend(id);
  }

  async #extend(id) {
    try {
      const fetched = await this.fetchers.yahoo(SYMBOLS[id].source.ticker);
      if (!fetched.length || this.#level(id) !== 'yahoo') return;
      this.store.set(id, mergeBars(fetched, this.store.get(id)));
    } catch {
      /* the recent bars will do; the store grows with every new bar */
    }
  }

  // Only real market data is saved.
  save() {
    if (!this.dir) return;
    try {
      fs.mkdirSync(this.dir, { recursive: true });
      for (const [id] of this.store) {
        if (!this.isReal(id)) continue;
        const rows = this.bars(id).slice(-MAX_BARS).map((b) => [b.time, b.open, b.high, b.low, b.close, Math.round(b.volume * 100) / 100]);
        if (!rows.length) continue;
        fs.writeFileSync(`${this.#cacheFile(id)}.tmp`, JSON.stringify({ v: CACHE_VERSION, level: this.#level(id), bars: rows }));
        fs.renameSync(`${this.#cacheFile(id)}.tmp`, this.#cacheFile(id));
      }
    } catch (err) {
      this.log.warn?.(`[research] saving history failed: ${err.message}`);
    }
  }

  stop() {
    clearInterval(this.saveTimer);
    this.save();
  }
}
