import fs from 'node:fs';
import path from 'node:path';
import { SYMBOLS } from '../market/symbols.js';
import { MarketData } from '../market/marketData.js';
import { SimFeed } from '../market/simFeed.js';
import { nyTimeOnSameDay, nyParts } from '../market/session.js';

// Long 1-minute history for the research desks (the live feeds only keep 15 hours).
//
// Live mode: about two weeks of real bars (Binance for crypto, Yahoo Finance for the rest),
// cached in data/history/ and extended with every new bar, so research gets better the
// longer the floor runs. Simulation mode (or a live market that fell back to simulation):
// past sessions are generated by the same market simulator, including the same economic
// calendar shocks, so the desks research the market they actually trade.

const MAX_BARS = 20_000;
const BINANCE_HOSTS = ['https://api.binance.com', 'https://data-api.binance.vision'];
const YAHOO_HOSTS = ['https://query1.finance.yahoo.com', 'https://query2.finance.yahoo.com'];
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126 Safari/537.36';

function mergeBars(a, b) {
  const map = new Map();
  for (const x of a) map.set(x.time, x);
  for (const x of b) map.set(x.time, x);
  return [...map.values()].sort((x, y) => x.time - y.time).slice(-MAX_BARS);
}

const isWeekend = (ms) => ['Sat', 'Sun'].includes(nyParts(ms).weekday);

const pause = () => new Promise((r) => setImmediate(r));

// Past simulated sessions ending just before `endSec`, for the given symbols (yields to the
// event loop between sessions so the floor stays responsive while it generates).
export async function syntheticHistory(ids, { endSec, sessions = 30, calendar = null, seed = 7, sessionShape = true, minutes = 12_000 }) {
  let t = 0;
  const clock = { now: () => t, mode: 'sim' };
  const md = new MarketData(clock);
  const out = Object.fromEntries(ids.map((id) => [id, []]));
  md.on('bar', (id, bar) => out[id]?.push(bar));
  const sim = new SimFeed(md, clock, ids, { seed, calendar, useSessionShape: sessionShape });
  if (sessionShape) {
    // Cash sessions 09:30–16:00 New York on the weekdays before endSec.
    const days = [];
    let d = endSec * 1000 - 86_400_000;
    while (days.length < sessions) {
      if (!isWeekend(d)) days.unshift(nyTimeOnSameDay(d, 16, 0));
      d -= 86_400_000;
    }
    let prevClose = null;
    for (const close of days) {
      const open = close - 390 * 60_000;
      if (prevClose) sim.gap(prevClose, open);
      t = close;
      sim.warmup(390);
      prevClose = close;
      await pause();
    }
  } else {
    for (let done = 0; done < minutes; done += 600) {
      const chunk = Math.min(600, minutes - done);
      t = endSec * 1000 - 60_000 - (minutes - done - chunk) * 60_000;
      sim.warmup(chunk);
      await pause();
    }
  }
  return out;
}

async function fetchJson(url, timeoutMs = 12_000, headers = {}) {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), timeoutMs);
  try {
    const res = await fetch(url, { signal: ctrl.signal, headers });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    return await res.json();
  } finally {
    clearTimeout(timer);
  }
}

async function binanceHistory(ticker, pages = 10) {
  let lastErr;
  for (const host of BINANCE_HOSTS) {
    try {
      let end = Date.now();
      let bars = [];
      for (let p = 0; p < pages; p++) {
        const rows = await fetchJson(`${host}/api/v3/klines?symbol=${ticker}&interval=1m&limit=1000&endTime=${end}`);
        if (!rows.length) break;
        bars = rows.map((k) => ({ time: Math.floor(k[0] / 1000), open: +k[1], high: +k[2], low: +k[3], close: +k[4], volume: +k[5] })).concat(bars);
        end = rows[0][0] - 1;
      }
      bars.pop(); // still forming
      return bars;
    } catch (err) {
      lastErr = err;
    }
  }
  throw lastErr;
}

async function yahooHistory(ticker, chunks = 2) {
  const now = Math.floor(Date.now() / 1000);
  let bars = [];
  let lastErr;
  for (let c = 0; c < chunks; c++) {
    const p2 = now - c * 7 * 86400;
    const p1 = p2 - 7 * 86400 + 60;
    let got = false;
    for (const host of YAHOO_HOSTS) {
      try {
        const json = await fetchJson(`${host}/v8/finance/chart/${encodeURIComponent(ticker)}?interval=1m&period1=${p1}&period2=${p2}&includePrePost=true`, 15_000, { 'User-Agent': UA, Accept: 'application/json' });
        const r = json?.chart?.result?.[0];
        const ts = r?.timestamp || [];
        const q = r?.indicators?.quote?.[0] || {};
        const chunk = [];
        for (let i = 0; i < ts.length; i++) {
          const close = q.close?.[i];
          if (close == null) continue;
          const open = q.open?.[i] ?? close;
          const time = Math.floor(ts[i] / 60) * 60;
          const prev = chunk[chunk.length - 1];
          if (prev && prev.time === time) {
            prev.high = Math.max(prev.high, q.high?.[i] ?? close);
            prev.low = Math.min(prev.low, q.low?.[i] ?? close);
            prev.close = close;
            continue;
          }
          chunk.push({ time, open, high: q.high?.[i] ?? Math.max(open, close), low: q.low?.[i] ?? Math.min(open, close), close, volume: q.volume?.[i] ?? 0 });
        }
        bars = mergeBars(bars, chunk);
        got = true;
        break;
      } catch (err) {
        lastErr = err;
      }
    }
    if (!got && c === 0) throw lastErr;
  }
  if (bars.length) bars.pop();
  return bars;
}

export class HistoryStore {
  constructor({ md, mode, dataDir = null, calendar = null, log = console, fetchers = null }) {
    this.md = md;
    this.mode = mode;
    this.calendar = calendar;
    this.log = log;
    this.dir = dataDir && mode !== 'sim' ? path.join(dataDir, 'history') : null;
    this.fetchers = fetchers || { binance: binanceHistory, yahoo: yahooHistory };
    this.store = new Map(Object.keys(SYMBOLS).map((id) => [id, []]));
    this.info = new Map(Object.keys(SYMBOLS).map((id) => [id, { source: 'none', status: 'waiting' }]));
    this.ready = false;
    md.on('bar', (id, bar) => this.#append(id, bar));
    md.on('rebase', (id, offset) => {
      for (const b of this.store.get(id) || []) {
        b.open += offset; b.high += offset; b.low += offset; b.close += offset;
      }
    });
  }

  #append(id, bar) {
    const arr = this.store.get(id);
    if (!arr) return;
    const lastBar = arr[arr.length - 1];
    if (lastBar && bar.time <= lastBar.time) return;
    arr.push({ time: bar.time, open: bar.open, high: bar.high, low: bar.low, close: bar.close, volume: bar.volume });
    if (arr.length > MAX_BARS + 500) arr.splice(0, arr.length - MAX_BARS);
  }

  // All stored bars with the feed's latest closed bars merged in (oldest first).
  bars(id) {
    const arr = this.store.get(id) || [];
    const live = this.md.bars(id);
    const lastT = arr.length ? arr[arr.length - 1].time : -Infinity;
    const tail = live.filter((b) => b.time > lastT);
    return tail.length ? arr.concat(tail) : arr;
  }

  recent(id, n) {
    const all = this.bars(id);
    return all.length > n ? all.slice(-n) : all;
  }

  status() {
    const out = {};
    for (const [id, arr] of this.store) out[id] = { ...this.info.get(id), bars: this.bars(id).length, from: arr[0]?.time ?? null };
    return out;
  }

  async load() {
    const ids = Object.keys(SYMBOLS);
    const simIds = ids.filter((id) => this.mode === 'sim' || this.md.get(id)?.source === 'sim');
    const liveIds = ids.filter((id) => !simIds.includes(id));
    if (simIds.length) await this.#loadSynthetic(simIds);
    await Promise.all(liveIds.map((id) => this.#loadLive(id)));
    this.ready = true;
    if (this.dir) {
      this.saveTimer = setInterval(() => this.save(), 15 * 60_000);
      this.saveTimer.unref?.();
    }
  }

  async #loadSynthetic(ids) {
    const first = Object.fromEntries(ids.map((id) => [id, this.md.bars(id)[0]]));
    const endSec = Math.min(...ids.map((id) => first[id]?.time ?? Math.floor(Date.now() / 1000)));
    const gen = await syntheticHistory(ids, {
      endSec, calendar: this.calendar, seed: (endSec % 100_000) + 17,
      sessionShape: this.mode === 'sim',
    });
    for (const id of ids) {
      let bars = gen[id] || [];
      // Line the generated history up with where the live simulation starts.
      const anchor = first[id]?.open;
      const lastBar = bars[bars.length - 1];
      if (anchor && lastBar) {
        const k = anchor / lastBar.close;
        bars = bars.map((b) => ({ ...b, open: b.open * k, high: b.high * k, low: b.low * k, close: b.close * k }));
      }
      bars = bars.filter((b) => b.time < endSec);
      this.store.set(id, mergeBars(bars, this.md.bars(id)));
      this.info.set(id, { source: 'simulated', status: 'ready' });
    }
  }

  #cacheFile(id) {
    return this.dir ? path.join(this.dir, `${id}.json`) : null;
  }

  async #loadLive(id) {
    const sym = SYMBOLS[id];
    let bars = [];
    try {
      const raw = JSON.parse(fs.readFileSync(this.#cacheFile(id), 'utf8'));
      bars = raw.map(([time, open, high, low, close, volume]) => ({ time, open, high, low, close, volume }));
    } catch {
      /* no cache yet */
    }
    let source = bars.length ? 'saved' : 'none';
    try {
      const fetched = sym.source.type === 'binance' ? await this.fetchers.binance(sym.source.ticker) : await this.fetchers.yahoo(sym.source.ticker);
      if (fetched.length) {
        bars = mergeBars(bars, fetched);
        source = sym.source.type;
      }
    } catch (err) {
      this.log.warn?.(`[research] ${id}: could not load long history (${err.message})${bars.length ? ' — using the saved copy' : ''}`);
    }
    // If the broker (MT5) owns the symbol, its price level differs: shift the history.
    const live = this.md.bars(id);
    if (bars.length && live.length && this.md.ownerOf(id)) {
      const ref = bars.find((b) => b.time >= live[0].time);
      if (ref) {
        const off = live[0].close - ref.close;
        bars = bars.filter((b) => b.time < live[0].time).map((b) => ({ ...b, open: b.open + off, high: b.high + off, low: b.low + off, close: b.close + off }));
      }
    }
    this.store.set(id, mergeBars(bars, live));
    this.info.set(id, { source, status: 'ready' });
  }

  save() {
    if (!this.dir) return;
    try {
      fs.mkdirSync(this.dir, { recursive: true });
      for (const [id] of this.store) {
        const rows = this.bars(id).slice(-MAX_BARS).map((b) => [b.time, b.open, b.high, b.low, b.close, Math.round(b.volume * 100) / 100]);
        fs.writeFileSync(`${this.#cacheFile(id)}.tmp`, JSON.stringify(rows));
        fs.renameSync(`${this.#cacheFile(id)}.tmp`, this.#cacheFile(id));
      }
    } catch (err) {
      this.log.warn?.(`[research] saving history failed: ${err.message}`);
    }
  }

  stop() {
    clearInterval(this.saveTimer);
    this.save();
  }
}
